/* Run: npm i && npx eslint . (or enable ESLint in your IDE) */
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import globals from "globals";
import eslintPluginPrettierRecommended from "eslint-plugin-prettier/recommended";

const sharedParserOptions = {
  ecmaVersion: "latest",
};

const commonRules = {
  "no-unused-vars": [
    "error",
    {
      argsIgnorePattern: "^_",
      varsIgnorePattern: "^_",
      caughtErrorsIgnorePattern: "^_",
    },
  ],
  "no-console": [
    "error",
    {
      allow: ["error"],
    },
  ],
};

// Same intent as commonRules, but uses the typescript-eslint version of
// no-unused-vars which understands type-only imports.
const commonRulesTs = {
  "@typescript-eslint/no-unused-vars": [
    "error",
    {
      argsIgnorePattern: "^_",
      varsIgnorePattern: "^_",
      caughtErrorsIgnorePattern: "^_",
    },
  ],
  "no-console": [
    "error",
    {
      allow: ["error"],
    },
  ],
};

export default [
  {
    ignores: [
      // Built by Vite to dist/item-metadata.js (gitignored)
      "dist/**",
      // Generated by scripts/fixture-builder.js (see script header).
      "tests/fixtures/**",
      "tmp/**",
      "spritesheets/**",
    ],
  },
  js.configs.recommended,
  // Scope typescript-eslint's recommended preset to .ts files only so it
  // doesn't apply TS-only rules (e.g. no-unused-expressions stricter than
  // the core one, which would reject chai's `expect(x).to.be.true`) to .js.
  ...tseslint.configs.recommended.map((cfg) => ({
    ...cfg,
    files: ["**/*.ts"],
  })),
  {
    files: ["**/*.js"],
    languageOptions: {
      parserOptions: {
        ...sharedParserOptions,
        sourceType: "module",
      },
      globals: {
        ...globals.node,
        ...globals.es2021,
      },
    },
    rules: commonRules,
  },
  {
    files: ["sources/**/*.js"],
    languageOptions: {
      parserOptions: {
        ...sharedParserOptions,
        sourceType: "module",
      },
      globals: {
        ...globals.browser,
        ...globals.es2021,
      },
    },
  },
  {
    files: ["sources/**/*.ts"],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.es2021,
      },
    },
    rules: {
      ...commonRulesTs,
      // Architecture layering enforcement (components → state → canvas → utils)
      // See ARCHITECTURE.md for the full dependency graph and rationale.
      "@typescript-eslint/no-restricted-imports": [
        "error",
        {
          paths: [],
          patterns: [
            // canvas/ must not import from state/ (except render-state.ts which is the shared render-state container)
            {
              group: ["../state/*", "../../state/*", "../../../state/*"],
              allowImportNames: ["renderState"],
              message:
                "canvas/ may only import render-state.ts from state/. All other state imports create circular dependencies.",
            },
            // utils/ must not import from components/, state/, or canvas/
            {
              group: [
                "../components/*",
                "../../components/*",
                "../state/*",
                "../../state/*",
                "../canvas/*",
                "../../canvas/*",
              ],
              message:
                "utils/ must not import from components/, state/, or canvas/. It is the bottom layer.",
            },
            // state/ must not import from components/
            {
              group: ["../components/*", "../../components/*"],
              message:
                "state/ must not import from components/. That reverses the intended layering.",
            },
          ],
        },
      ],
    },
  },
  {
    files: ["tests/**/*.js"],
    ignores: ["tests/visual/**"],
    languageOptions: {
      parserOptions: {
        ...sharedParserOptions,
        sourceType: "module",
      },
      globals: {
        ...globals.browser,
        ...globals.es2021,
        ...globals.mocha,
        m: "readonly",
      },
    },
  },
  {
    files: ["tests/**/*.ts"],
    ignores: ["tests/visual/**"],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.es2021,
        ...globals.mocha,
        m: "readonly",
      },
    },
    rules: commonRulesTs,
  },
  {
    files: ["tests/visual/**/*.js"],
    languageOptions: {
      parserOptions: {
        ...sharedParserOptions,
        sourceType: "module",
      },
      globals: {
        ...globals.node,
        ...globals.browser,
        ...globals.es2021,
      },
    },
  },
  {
    files: ["playwright.config.js", "vite.config.js", "vite/**/*.js"],
    languageOptions: {
      parserOptions: {
        ...sharedParserOptions,
        sourceType: "module",
      },
      globals: {
        ...globals.node,
        ...globals.es2021,
      },
    },
  },
  {
    files: ["**/*.cjs"],
    languageOptions: {
      parserOptions: {
        ...sharedParserOptions,
        sourceType: "commonjs",
      },
      globals: {
        ...globals.node,
        ...globals.es2021,
      },
    },
    rules: commonRules,
  },
  {
    ...eslintPluginPrettierRecommended,
    files: ["**/*.{js,cjs,ts}"],
  },
];
